language: php

php:
  - 5.5.9
  - 5.6
  - hhvm

env:
  global:
    - setup=stable

matrix:
  include:
    - php: 5.5.9
      env: setup=stable
    - php: 5.6
      env: setup=stable

sudo: false

before_install: composer selfupdate
install: travis_retry composer install --no-interaction --ignore-platform-reqs --no-scripts --prefer-source
script: vendor/bin/phpunit